import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { flattenTokens } from "./lib/token-utils.mjs";
import { rootDir } from "./lib/workflow-utils.mjs";

export { flattenTokens } from "./lib/token-utils.mjs";

const inputPath = path.join(rootDir, "tokens", "figma-variables.json");
const cssOutPath = path.join(rootDir, "tokens", "tokens.css");
const tsOutPath = path.join(rootDir, "tokens", "tokens.ts");

function buildCss(tokens) {
  const lines = [
    "/* Generated by scripts/build-tokens.mjs */",
    ":root {",
    ...tokens.map((token) => `  --${token.name}: ${token.value};`),
    "}",
    ""
  ];
  return lines.join("\n");
}

function buildTs(tokens) {
  const entries = tokens
    .map((token) => `  "${token.name}": "var(--${token.name})"`)
    .join(",\n");

  const names = tokens.map((token) => `  "${token.name}"`).join(",\n");

  return [
    "/* Generated by scripts/build-tokens.mjs */",
    "export const tokens = {",
    entries,
    "} as const;",
    "",
    "export type TokenName = keyof typeof tokens;",
    "",
    "export const tokenNames: readonly TokenName[] = [",
    names,
    "] as const;",
    ""
  ].join("\n");
}

export async function buildArtifacts() {
  const raw = await fs.readFile(inputPath, "utf8");
  const json = JSON.parse(raw);
  const flattened = flattenTokens(json);

  if (flattened.length === 0) {
    throw new Error("No tokens found in tokens/figma-variables.json");
  }

  const css = buildCss(flattened);
  const ts = buildTs(flattened);

  await fs.writeFile(cssOutPath, css, "utf8");
  await fs.writeFile(tsOutPath, ts, "utf8");

  return { count: flattened.length, cssOutPath, tsOutPath };
}

async function main() {
  const result = await buildArtifacts();
  console.log(`Built ${result.count} tokens:`);
  console.log(`- ${path.relative(rootDir, result.cssOutPath)}`);
  console.log(`- ${path.relative(rootDir, result.tsOutPath)}`);
}

if (path.resolve(process.argv[1] || "") === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
