/* Generated by scripts/build-tokens.mjs */
export const tokens = {
  "color-brand-primary": "var(--color-brand-primary)",
  "color-brand-surface": "var(--color-brand-surface)",
  "color-brand-text": "var(--color-brand-text)",
  "space-xs": "var(--space-xs)",
  "space-sm": "var(--space-sm)",
  "space-md": "var(--space-md)",
  "space-lg": "var(--space-lg)",
  "space-xl": "var(--space-xl)",
  "size-border-default": "var(--size-border-default)",
  "radius-sm": "var(--radius-sm)",
  "radius-md": "var(--radius-md)",
  "shadow-card": "var(--shadow-card)",
  "font-family-base": "var(--font-family-base)",
  "font-size-body": "var(--font-size-body)",
  "font-size-title": "var(--font-size-title)",
  "font-letter-spacing-kicker": "var(--font-letter-spacing-kicker)",
  "font-weight-regular": "var(--font-weight-regular)",
  "font-weight-bold": "var(--font-weight-bold)"
} as const;

export type TokenName = keyof typeof tokens;

export const tokenNames: readonly TokenName[] = [
  "color-brand-primary",
  "color-brand-surface",
  "color-brand-text",
  "space-xs",
  "space-sm",
  "space-md",
  "space-lg",
  "space-xl",
  "size-border-default",
  "radius-sm",
  "radius-md",
  "shadow-card",
  "font-family-base",
  "font-size-body",
  "font-size-title",
  "font-letter-spacing-kicker",
  "font-weight-regular",
  "font-weight-bold"
] as const;
